---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-local-pvc
  labels:
    type: local
spec:
  storageClassName: prometheus-local-pvc
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k8s-data/raid1/prometheus"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-local-pvc
  labels:
    type: local
spec:
  storageClassName: grafana-local-pvc
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k8s-data/raid1/grafana"