---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-config-local-pv
  labels:
    type: local
spec:
  storageClassName: code-config-local-pv
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k8s-data/raid1/code-config"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-config-local-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: code-config-local-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: code-local-pv
  labels:
    type: local
spec:
  storageClassName: code-local-pv
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k8s-data/hub-workdir/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-local-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: code-local-pv