# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "local" {
    path = "/home/szymonri/Documents/helmfile-cluster/terraform/components/vpn_droplet/../../tfstate/terraform.tfstate"
  }
}
