

basepath: ""

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"
  rules:
    - host: auth.szymonrichert.pl
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - auth.szymonrichert.pl
      secretName: keycloak-tls

resources:
  requests:
    cpu: 500m
    memory: 1024Mi
  limits:
    cpu: "1"
    memory: 2048Mi

postgresql:
  securityContext:
    enabled: true
    fsGroup: 1000
  containerSecurityContext:
    enabled: true
    runAsUser: 1000
  persistence:
    storageClass: keycloak-raid1-pv
    accessModes:
      - ReadWriteOnce
    size: 2Gi
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 250m
      memory: 512Mi