extraEnv: ENC[AES256_GCM,data:Lpa/jZcBCnzNPboTQo3udTDWaP5S6MSkJ/IQy8ACz0sb48z4SJBKSbSNaiYPmHDmKHdUHBajt6Cs6DWQXjqu5sVz5ctZdO2lk26oD5A1925U8TKv4Y9VQvvOv+HzhhUHplL5xOb0hPa23jeWOklqS+7Bl5R0VrtkfxUhgw1+ZD8FLt9f7xCxfWQusAU=,iv:Qy4tms6sw+vzytTKklCso/1HSgn7Uhz7dbO7RvQugHo=,tag:FTjyO0jGONrFB4TYv/iLGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-10-25T20:43:27Z'
    mac: ENC[AES256_GCM,data:kdmMTwFHDeE9DOtzojLpxq7UcJ5Qpb63G/KbV5D7SMyftVTlt1aLHxORxg3vYlpvrlB8+9gKKEexWuwvNAslMP1ioYk6FJA11yeh8I61D1lTN0G9E665QoAdb1mNR05mdSk60VPbO4NkAk7xaMQb+LvEUT+NnlpcIwGtSM1BTp8=,iv:/zzM4QYvi69jOk1ztaw7UxGebmN27pYX2h9QVF/c2iM=,tag:p6o79BtV7kDPjbVnapw8nQ==,type:str]
    pgp:
    -   created_at: '2021-10-25T20:43:26Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwGxy666b7DTARAAx2Uy7OTASciuGtYFgD8GvHbhQ0WCyyKVjocb9B/jzFZh
            3fEPB1BFWlI7OaLGco2JiolxGnPMp9l7OJbSRzpdoZv3G1upZ/YpXhhr4aZNGUbD
            4HkRASh7R+Je1gHm6EybWgUvxHWiqY2SFkfvAPLf2dkpTV8mP64c+/FAm5HVOeQ7
            XvxX8eg2CfhEa9/5xT4gJf39p/xDqYYe7DYCGbaXveeX5P+eeOTWiYGmNgaoFBUI
            zPItrC5ElnsJMlzMs489vehXU7J754z7lYwwt60LamwfUE1ARUmRSlSEbT7OFOi7
            YyFnz/+PMynpthwY1gvspGb4CikNF06kN1kwhHLXsBSSr1TSHWcbVsrWArg6DYPG
            JhnK7TRYddkCDNofDUpjf4Aa/jHSXU8QMIMh9zO9w/HWLmFGcI0XfqmGOUPxigZF
            s9/IllgHoWQ5khw2OLUriKxNNKzQQFbChVdUgzJD6fdXF25+sRM6AXm+ZaqDV0+9
            BPoV+yI0BuVdIizt5fUcJFZcY9X5xjUyiFSODZyR3T8MupL2cugzm/gLTNl1mqbM
            ZkjBSEGUdfepWyW2r2mGI45rJPcSzCSbNjBpY9sAVPL2FPddXz292SmVBsRx9wdS
            aoqGSX6EHHwjPio5W8XQ+vkI21pWhcJGj7nMYJhk8oxQB+/jOJWDgKvkTg1haZXS
            XgGNb4uPJQbSRYPilTYDLC6vq9uH+tWd9/6QSYBybw99HhZjLQT/Z4LYP37H7riD
            yRO9lErPiJpLgGo4ZuTzhIl1thqVj21MfQB8BDT94c1B8Vc85x+Hvz0W1fA1V+E=
            =LpdD
            -----END PGP MESSAGE-----
        fp: D39E46932A270AA3BA490B9DB9FE928D3E8BCED8
    unencrypted_suffix: _unencrypted
    version: 3.6.0
