---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-local-pv
  labels:
    type: local
spec:
  storageClassName: wordpress-local-pv
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k8s-data/raid1/wordpress"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-local-pv
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: wordpress-local-pv
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-db-local-pv
  labels:
    type: local
spec:
  storageClassName: wordpress-db-local-pv
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k8s-data/raid1/wordpress-db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-db-local-pv
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: wordpress-db-local-pv
