config:
    githubPersonalToken: ENC[AES256_GCM,data:81c0mqII+i/SwBn/73f+lJ+1Gkc2Qvgu3tIgjqJuQ+TwCk31Q1GZcw==,iv:LyYk8KlQhUN0v0bxZMaFQsRbvZIIOE7cK8LcbwQFB0w=,tag:/QoLhArDU0N3fEHtbjbDeQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    lastmodified: '2022-06-13T08:04:17Z'
    mac: ENC[AES256_GCM,data:iJOou/EyfPJIXQ4UXW/XJPdmrSgNtEk/WhiX6f+h9t2kHvg6S6xMfS6wqOkVVn8Mse4eK73lcCtsJ7h5mmIpU0QnVO1yzcU38bV5W04RB7fiDX65B9Fl+Hx2GsNw7tb+jp5cKw+9YmLt4qgxHTMgOZPcAKZehZBE/1XRsdLNh20=,iv:LVgx6y6F/4xLJdq4E4p0xVyr9jkndYDZM4ayJGCqExU=,tag:OVqyUemrPhgj70+RVSXt6g==,type:str]
    pgp:
    -   created_at: '2022-06-13T08:04:16Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAwGxy666b7DTAQ/7B1C+e0z1zC71ETSUPFuBfdEYtsYy3QB2n2za60u8wC63
            1oH46SyxGD2Wfa24FV5xakBuz5OjuWytvjXhv8odwCur5RpMsJLT2oTNscthF8fg
            FsZI5lxhrRI0CPb4D752mENpVOtfkMdBaYVtlU5KfWJ+OmQPIESJTbkvgPqJ4YR9
            cHUW0K32WuM7KBKUlobT8JGhih3fd7tzy/mV4yApCNBXpKsKl6akpVyVNRdxVUv2
            MaCBNLQHK/dNX1Fiti2XwtUABAi/BwKkRJzl34bV7nDtVq367Gm1l2neLqF2jVQH
            6o6Mr+J8CEV0qt0mzl+d8dlRQixtECMJiRu3kv6edUY7AaxEn4/B3Rc1b57S8uQW
            ig4vfkJtvbSAQrOeTvwuWlvgifRLe+/sEh+rLUhVsoERsQjrLNGbBM8ps7IEpXSV
            V6a8hyuyues/VXSdDJIClot4TPXmrWMjJRLc2sBnCMI1cdhPaHbMzAxvr0PC78/z
            WPGvoXQG5B6c8nUA38tj9OQbLYwa6dY1LGnLKq7UnIOBEVVjg2qYBFXjtqbRaCPX
            eo6WqfeOpGfifWt6L6W2f51Z/ohLbTZyIM3y+BetgKD0r+uWHwXd1CI9x/xeoWzc
            /VMgQ5guEyq2mYyMMBjMYKpORTcEqdBpVcMdfI3YBgov3L62bqmVq6IbwqZ7t0PS
            XgHc6cLRKRD4QkbGHZBFTq2eF+zwmlRy7W5ZP0tEsIJihnI85UgJdVaf0WZmic12
            MLkwXtjxaqFQItMdM9z3lnMRGunjFFtZphxA6rSVrJMsSA29gVrCPtmzgQjElJE=
            =rQ4f
            -----END PGP MESSAGE-----
        fp: D39E46932A270AA3BA490B9DB9FE928D3E8BCED8
    unencrypted_suffix: _unencrypted
    version: 3.0.3
