---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterhub-db-local-pv
  labels:
    type: local
spec:
  storageClassName: jupyterhub-db-local-pv
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k8s-data/raid1/jupyterhub-db"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyterhub-local-pv
  labels:
    type: local
spec:
  storageClassName: jupyterhub-local-pv
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k8s-data/hub-workdir/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyterhub-local-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: jupyterhub-local-pv