---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-raid1-pv
  labels:
    type: local
spec:
  storageClassName: keycloak-raid1-pv
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k8s-data/raid1/keycloak-postgresql"
