name: autoupgrade

on:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup tools
      run: |
        sudo pip3 install ruamel.yaml

    - name: Diff
      env:
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      run: |
        set -e
        echo $ENCRYPTION_KEY | base64 --decode > encryption_key.gpg
        gpg --import encryption_key.gpg
        sops -d -i ./kubeconfig
        export KUBECONFIG="$(pwd)/kubeconfig"
        environment="$(yq e '.environments | keys | .[0]' helmfile.yaml)"
        helmfile -e $environment diff || true
