initContainers:
  custom-webui:
    name: custom-webui
    image: curlimages/curl:7.76.1
    command:
    - "/bin/sh"
    - "-c"
    - "curl -o- -sL https://github.com/johman10/flood-for-transmission/releases/download/latest/flood-for-transmission.tar.gz | tar xzf - -C /config"
    volumeMounts:
    - name: config
      mountPath: /config
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000

additionalContainers:
  oauth2proxy:
    env:
    - name: OAUTH2_PROXY_PROVIDER
      value: keycloak-oidc
    - name: OAUTH2_PROXY_CLIENT_ID
      valueFrom:
        secretKeyRef:
          key: oidc-session-id
          name: transmission
    - name: OAUTH2_PROXY_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          key: oidc-session-secret
          name: transmission
    - name: OAUTH2_PROXY_REDIRECT_URL
      value: https://transmission.szymonrichert.pl/oauth2/callback
    - name: OAUTH2_PROXY_OIDC_ISSUER_URL
      value: https://auth.szymonrichert.pl/auth/realms/Lab
    - name: OAUTH2_PROXY_HTTP_ADDRESS
      value: 0.0.0.0:4180
    - name: OAUTH2_PROXY_REVERSE_PROXY
      value: "true"
    - name: OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER
      value: "true"
    - name: OAUTH2_PROXY_PASS_ACCESS_TOKEN
      value: "true"
    - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
      value: "true"
    - name: OAUTH2_PROXY_UPSTREAMS
      value: http://localhost:9091
    - name: OAUTH2_PROXY_COOKIE_NAME
      value: oauth2-authorization-cookie
    - name: OAUTH2_PROXY_COOKIE_DOMAIN
      value: szymonrichert.pl
    - name: OAUTH2_PROXY_EMAIL_DOMAINS
      value: '*'
    - name: OAUTH2_PROXY_COOKIE_SECRET
      valueFrom:
        secretKeyRef:
          key: oidc-cookie-secret
          name: transmission
    image: quay.io/oauth2-proxy/oauth2-proxy:v7.3.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: http-oidc
      timeoutSeconds: 1
    name: oauth2proxy
    ports:
    - containerPort: 4180
      name: http-oidc
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      periodSeconds: 10
      successThreshold: 1
      tcpSocket:
        port: http-oidc
      timeoutSeconds: 1
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    securityContext:
      runAsUser: 1000
      runAsGroup: 1000

env:
  TZ: UTC
  TRANSMISSION_WEB_HOME: /web
  TRANSMISSION_RPC_PASSWORD: "*oik4sahx9EeKae5!"
  TRANSMISSION_DOWNLOAD_DIR: /downloads/transmission-complete
  TRANSMISSION_INCOMPLETE_DIR_ENABLED: false
  TRANSMISSION_INCOMPLETE_DIR: /downloads/transmission-incomplete
  TRANSMISSION_WATCH_DIR_ENABLED: false
  TRANSMISSION_WATCH_DIR: /watch

ingress:
  main:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: transmission.szymonrichert.pl
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: transmission-tls
        hosts:
          - transmission.szymonrichert.pl

service:
  main:
    ports:
      http:
        port: 4180
        targetPort: 4180

podSecurityContext:
  fsGroup: 1000
  runAsGroup: 1000
  runAsNonRoot: false
  runAsUser: 1000

hostNetwork: false
# dnsPolicy: "None"
# dnsConfig:
#   nameservers:
#     - 8.8.8.8
#     - 1.1.1.1

resources:
  limits:
    cpu: 250m
    memory: 2Gi
  requests:
    cpu: 100m
    memory: 128Mi

persistence:
  config:
    enabled: true
    type: hostPath
    mountPath: /config
    hostPath: /k8s-data/raid1/transmission-config
  downloads:
    enabled: true
    type: hostPath
    mountPath: /downloads
    hostPath: /k8s-data/disk
