
wordpressEmail: szymon.rychu@gmail.com
wordpressFirstName: Szymon
wordpressLastName: Richert
wordpressBlogName: szymonrichert.pl
smtpHost: smtp.gmail.com
smtpPort: 465
smtpProtocol: tls

ingress:
  enabled: true
  pathType: Prefix
  ingressClassName: nginx
  hostname: www.szymonrichert.pl
  path: /
  tls: true
  extraHosts:
    - name: blog.szymonrichert.pl
      path: /
  extraTls:
    - hosts:
        - blog.szymonrichert.pl
      secretName: blog.szymonrichert.pl-tls
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/tls-acme: "true"

podSecurityContext:
  enabled: true
  fsGroup: 1000
containerSecurityContext:
  enabled: true
  runAsUser: 1000
  runAsNonRoot: true

resources:
  limits:
    memory: 1Gi
    cpu: 500m
  requests:
    memory: 512Mi
    cpu: 300m

service:
  ## @param service.type WordPress service type
  ##
  type: ClusterIP

metrics:
  enabled: true
  resources:
    limits:
      memory: 128Mi
      cpu: 100m
    requests:
      memory: 128Mi
      cpu: 100m

persistence:
  enabled: true
  existingClaim: wordpress-local-pv

mariadb:
  primary:
    podSecurityContext:
      enabled: true
      fsGroup: 1000
    containerSecurityContext:
      enabled: true
      runAsUser: 1000
      runAsNonRoot: true
    persistence:
      enabled: true
      existingClaim: wordpress-db-local-pv
    resources:
      limits:
        memory: 512Mi
        cpu: 500m
      requests:
        memory: 128Mi
        cpu: 100m