#!/bin/bash -e


if ! env | grep "ENCRYPTION_PASSWORD" > /dev/null; then
    echo "Please provide ENCRYPTION_PASSWORD!"
    exit 1
fi

THIS_FULL_PATH=$(python3 -c "import os; print(os.path.realpath('$0'))")
REPO_DIR=$(dirname $(dirname $THIS_FULL_PATH))

if [ -f $REPO_DIR/terraform/tfstate/terraform.tfstate.enc ]; then
    cp -f $REPO_DIR/terraform/tfstate/terraform.tfstate.enc $REPO_DIR/terraform/tfstate/terraform.tfstate
    $REPO_DIR/scripts/local_decrypt $REPO_DIR/terraform/tfstate/terraform.tfstate
fi

find $REPO_DIR/terraform/ -name 'secrets.tfvars.enc' | xargs -I {} bash -ce "\
    cp -f {} \$(dirname {})/\$(basename {} .enc);\
    $REPO_DIR/scripts/local_decrypt \$(dirname {})/\$(basename {} .enc) \
    "
find $REPO_DIR/terraform/ -name '*_secrets.tfvars' | xargs -I {} bash -ce "\
    cp -f {} \$(dirname {})/\$(basename {} .enc);\
    $REPO_DIR/scripts/local_decrypt \$(dirname {})/\$(basename {} .enc) \
    "
sleep 1