ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: esphome.szymonrichert.pl
        paths:
          - path: /
    tls:
      - secretName: esphome-tls
        hosts: 
          - esphome.szymonrichert.pl

persistence:
  config:
    enabled: true
    type: hostPath
    mountpath: /config
    hostPath: /k8s-data/raid1/filebrowser