---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: influxdb-raid1-pv
  labels:
    type: local
spec:
  storageClassName: influxdb-raid1-pvc
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/k8s-data/raid1/home-assistant-influxdb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-raid1-pvc
spec:
  storageClassName: influxdb-raid1-pvc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi