image:
  repository: docker.io/emby/embyserver
  pullPolicy: IfNotPresent
  tag: 4.7.0.12

ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      kubernetes.io/tls-acme: "true"
    hosts:
      - host: emby.szymonrichert.pl
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: emby-tls
        hosts:
          - emby.szymonrichert.pl

podSecurityContext:
  fsGroup: 1000
  # runAsGroup: 1000
  # runAsNonRoot: true
  # runAsUser: 1000

env:
  NVIDIA_VISIBLE_DEVICES: GPU-75e37533-e1a4-88d2-f573-dca6ce27d047

metrics:
  enabled: true

hostNetwork: true

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 4
    memory: 4096Mi

persistence:
  config:
    enabled: true
    type: hostPath
    mountPath: /config
    hostPath: /k8s-data/raid1/emby-config
  transcoding:
    enabled: true
    type: hostPath
    mountPath: /config/transcoding-temp
    hostPath: /k8s-data/emby-transcoding-temp
  movies:
    enabled: true
    type: hostPath
    mountPath: /media/movies
    hostPath: /k8s-data/disk/movies
  tvseries:
    enabled: true
    type: hostPath
    mountPath: /media/tvseries
    hostPath: /k8s-data/disk/tvseries
  music:
    enabled: true
    type: hostPath
    mountPath: /media/music
    hostPath: /k8s-data/disk/music
