---
# tasks file for openvpn

- name: import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install openvpn packages
  ansible.builtin.package:
    name: "{{ openvpn_packages }}"
    state: present

- name: setup openvpn server or client
  ansible.builtin.include_tasks:
    file: "{{ openvpn_role }}.yml"
