---

- name: ensure /etc/openvpn/easy-rsa exists
  ansible.builtin.file:
    path: /etc/openvpn/easy-rsa
    state: directory
    mode: "0755"

- name: ensure /etc/openvpn/ccd exists
  ansible.builtin.file:
    path: /etc/openvpn/ccd
    state: directory
    mode: "0755"

- name: easyrsa init-pki
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_path }}/easyrsa init-pki"
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki

- name: easyrsa build-ca
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_path }}/easyrsa build-ca nopass"
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/ca.crt
  environment:
    EASYRSA_BATCH: "yes"

- name: easyrsa gen-dh
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_path }}/easyrsa gen-dh"
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/dh.pem

- name: easyrsa build-server-full server nopass
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_path }}/easyrsa build-server-full server nopass"
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/issued/server.crt

- name: easyrsa build-client-full client nopass
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_path }}/easyrsa build-client-full client nopass"
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/issued/client.crt

- name: easyrsa build-client-full additional clients nopass
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_path }}/easyrsa build-client-full {{ item }} nopass"
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/issued/{{ item }}.crt
  with_items: "{{ openvpn_additional_clients }}"

- name: easyrsa gen-crl
  ansible.builtin.command:
    cmd: "{{ openvpn_easyrsa_path }}/easyrsa gen-crl"
    chdir: /etc/openvpn/easy-rsa
    creates: /etc/openvpn/easy-rsa/pki/crl.pem

- name: openvpn --genkey --secret /etc/openvpn/easy-rsa/pki/ta.key
  ansible.builtin.command:
    cmd: openvpn --genkey --secret /etc/openvpn/easy-rsa/pki/ta.key
    creates: /etc/openvpn/easy-rsa/pki/ta.key

- name: copy files to /etc/openvpn/server
  ansible.builtin.copy:
    src: /etc/openvpn/easy-rsa/pki/{{ item }}
    dest: /etc/openvpn/server/{{ item | basename }}
    mode: "0640"
    remote_src: yes
  loop:
    - ca.crt
    - dh.pem
    - ta.key
    - issued/client.crt
    - issued/server.crt
    - private/ca.key
    - private/client.key
    - private/server.key

- name: copy additional_clients certs
  ansible.builtin.copy:
    src: /etc/openvpn/easy-rsa/pki/issued/{{ item }}.crt
    dest: /etc/openvpn/server/{{ item }}.crt
    mode: "0640"
    remote_src: yes
  with_items: "{{ openvpn_additional_clients }}"
  notify:
    - restart openvpn

- name: copy additional_clients keys
  ansible.builtin.copy:
    src: /etc/openvpn/easy-rsa/pki/private/{{ item }}.key
    dest: /etc/openvpn/server/{{ item }}.key
    mode: "0640"
    remote_src: yes
  with_items: "{{ openvpn_additional_clients }}"
  notify:
    - restart openvpn

- name: Enable net.ipv4.ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: place server.conf
  ansible.builtin.template:
    src: server.conf.j2
    dest: "{{ openvpn_configuration_directory }}/server.conf"
    owner: root
    group: "{{ openvpn_group }}"
    mode: "0640"
  notify:
    - restart openvpn

- name: create ccds
  ansible.builtin.template:
    src: ccd.j2
    dest: "/etc/openvpn/ccd/{{ item }}"
    owner: root
    group: "{{ openvpn_group }}"
    mode: "0640"
  vars:
    num: "{{ lookup('ansible.utils.index_of', openvpn_additional_clients, 'eq', item) }}"
  with_items: "{{ openvpn_additional_clients }}"
  notify:
    - restart openvpn

- name: create /etc/systemd/system/iptablesvpn.service
  ansible.builtin.template:
    src: iptablesvpn.service.j2
    dest: /etc/systemd/system/iptablesvpn.service
    owner: root
    group: root
    mode: "0640"

- name: create /etc/systemd/system/iptablesvpn.service
  ansible.builtin.template:
    src: iptablesvpn.service.j2
    dest: /etc/systemd/system/iptablesvpn.service
    owner: root
    group: root
    mode: "0640"
  notify:
    - restart iptablesvpn

- name: install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: create /etc/nginx/nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: "0640"
  notify:
    - restart nginx