name: diff

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Turnstyle
      uses: softprops/turnstyle@v1
      with:
        continue-after-seconds: 180
        poll-interval-seconds: 10
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup tools
      run: |
        sudo wget -qO /usr/local/bin/kubectl "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" > /dev/null 2>&1
        sudo chmod +x /usr/local/bin/kubectl

        sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod a+x /usr/local/bin/yq

        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash > /dev/null 2>&1
        (helm plugin install https://github.com/databus23/helm-diff || helm plugin update diff) > /dev/null 2>&1
        (helm plugin install https://github.com/futuresimple/helm-secrets || helm plugin update secrets) > /dev/null 2>&1

        curl -s https://api.github.com/repos/roboll/helmfile/releases/latest | jq -r '.assets[] | .browser_download_url' | grep 'linux_amd64' | xargs sudo wget -qO /usr/local/bin/helmfile
        sudo chmod +x /usr/local/bin/helmfile

    - name: Diff
      env:
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      run: |
        set -e
        echo $ENCRYPTION_KEY | base64 --decode > encryption_key.gpg
        gpg --import encryption_key.gpg
        sops -d -i ./kubeconfig
        export KUBECONFIG="$(pwd)/kubeconfig"
        environment="$(yq e '.environments | keys | .[0]' helmfile.yaml)"
        helmfile -e $environment diff || true
