name: diff

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: [self-hosted, linux, X64]
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Terraform plan
      run: |
        set -e

        ./terraform/decrypt.sh

        cd ./terraform/components/vpn_droplet

        terragrunt plan

        terragrunt output -json | jq -r '.ipv4_address.value' > /tmp/droplet_ipv4

    - name: Ansible
      run: |
        set -e
        cd ./ansible

        cat <<EOF > hosts
        [openvpn_server]
        $(cat /tmp/droplet_ipv4)    ansible_connection=ssh  ansible_user=vpn

        [openvpn_clients]
        192.168.1.25         ansible_connection=ssh  ansible_user=szymonri
        EOF

        ansible-playbook site.yml -i hosts --check

    - name: Diff
      env:
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      run: |
        set -e
        helmfile diff || true
