name: sync

on:
  push:
    branches:
      - master
  release:
    types:
      - created

jobs:
  build:
    runs-on: [self-hosted, linux, X64]
    steps:

    - name: Turnstyle
      uses: softprops/turnstyle@v1
      with:
        continue-after-seconds: 180
        poll-interval-seconds: 10
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sync
      env:
        ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
      run: |
        set -e
        echo $ENCRYPTION_KEY | base64 --decode > encryption_key.gpg
        gpg --import encryption_key.gpg
        sops -d -i ./kubeconfig
        export KUBECONFIG="$(pwd)/kubeconfig"
        helmfile apply
